[[main]]
  name = "Posts"
  url = "/posts/"
  weight = 10

[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[main]]
  name = "Gear"
  url = "/gear/"
  weight = 25

[[main]]
  name = "About"
  url = "/about/"
  weight = 30

[[main]]
  name = "Search"
  url = "/search/"
  weight = 40

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 50
